name: lm_camera
description: "Lightweight camera service for field workforce apps â€” captures photo with GPS & timestamp burned onto image."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  geolocator: ^9.0.2
  image: ^4.0.17
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
